--magnitude analysis i.e measure by dimension

--find total customers by country
select 
country,
COUNT(customer_key) as total_customers
from gold.dim_customers
group by country
order by total_customers desc


--find total customers by gender
select 
gender,
COUNT(customer_key) as total_customers
from gold.dim_customers
group by gender
order by total_customers desc


--find total products by category
select 
category,
count(product_key) as total_products
from gold.dim_products
group by category
order by total_products desc

--what is the average cost of each category
select
category,
AVG(cost) as average_cost
from gold.dim_products
group by category
order by average_cost desc


--Total revenue generated for each category
select
p.category,
sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key=f.product_key
group by p.category
order by total_revenue desc 

--Total revenue generated by each customer
select
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_customers c
on c.customer_key=f.customer_key
group by c.customer_key,
c.first_name,
c.last_name
order by total_revenue desc

--what is the distribution of sold items across countries
select
c.country,
SUM(f.quantity) as total_quantity
from gold.fact_sales f
left join gold.dim_customers c
on c.customer_key=f.customer_key
group by c.country
order by total_quantity desc
